import type { IconType } from "react-icons";
import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiNodedotjs,
  SiPostgresql,
  SiPrisma,
  SiDocker,
  SiPython,
  SiTailwindcss,
  SiHtml5,
  SiGit,
  SiGithub,
  SiGitlab,
  SiLinux,
  SiNginx,
  SiWireshark,
  SiKalilinux,
  SiMetasploit,
  SiSqlite,
  SiVercel,
  SiFigma,
  SiMysql,
  SiMongodb,
  SiRedis,
  SiGraphql,
  SiExpress,
  SiVuedotjs,
  SiAngular,
  SiPhp,
  SiLaravel,
  SiDjango,
  SiFlask,
  SiRust,
  SiGo,
  SiKubernetes,
  SiGooglecloud,
  SiOwasp,
  SiBurpsuite,
  SiHackthebox,
  SiTryhackme,
  SiPortswigger,
  SiZod,
  SiJsonwebtokens,
  SiOpenssl,
  SiUbuntu,
  SiDebian,
  SiApache,
  SiJest,
  SiEslint,
  SiPrettier,
  SiApple,
  SiAndroid,
} from "react-icons/si";
import { FaCss3Alt, FaAws, FaWindows } from "react-icons/fa6";

const TECH_ICONS: Record<string, { Icon: IconType; color: string }> = {
  react: { Icon: SiReact, color: "#61DAFB" },
  "next.js": { Icon: SiNextdotjs, color: "#FFFFFF" },
  nextjs: { Icon: SiNextdotjs, color: "#FFFFFF" },
  typescript: { Icon: SiTypescript, color: "#3178C6" },
  javascript: { Icon: SiJavascript, color: "#F7DF1E" },
  "node.js": { Icon: SiNodedotjs, color: "#5FA04E" },
  nodejs: { Icon: SiNodedotjs, color: "#5FA04E" },
  postgresql: { Icon: SiPostgresql, color: "#4169E1" },
  postgres: { Icon: SiPostgresql, color: "#4169E1" },
  prisma: { Icon: SiPrisma, color: "#8A9BA8" },
  docker: { Icon: SiDocker, color: "#2496ED" },
  python: { Icon: SiPython, color: "#3776AB" },
  "tailwind css": { Icon: SiTailwindcss, color: "#06B6D4" },
  tailwindcss: { Icon: SiTailwindcss, color: "#06B6D4" },
  html5: { Icon: SiHtml5, color: "#E34F26" },
  html: { Icon: SiHtml5, color: "#E34F26" },
  css3: { Icon: FaCss3Alt, color: "#1572B6" },
  css: { Icon: FaCss3Alt, color: "#1572B6" },
  git: { Icon: SiGit, color: "#F05032" },
  github: { Icon: SiGithub, color: "#FFFFFF" },
  gitlab: { Icon: SiGitlab, color: "#FC6D26" },
  linux: { Icon: SiLinux, color: "#FCC624" },
  nginx: { Icon: SiNginx, color: "#009639" },
  wireshark: { Icon: SiWireshark, color: "#1679A7" },
  "kali linux": { Icon: SiKalilinux, color: "#557C94" },
  kali: { Icon: SiKalilinux, color: "#557C94" },
  metasploit: { Icon: SiMetasploit, color: "#2596CD" },
  sqlite: { Icon: SiSqlite, color: "#7DA1C4" },
  vercel: { Icon: SiVercel, color: "#FFFFFF" },
  figma: { Icon: SiFigma, color: "#F24E1E" },
  mysql: { Icon: SiMysql, color: "#4479A1" },
  mongodb: { Icon: SiMongodb, color: "#47A248" },
  redis: { Icon: SiRedis, color: "#FF4438" },
  graphql: { Icon: SiGraphql, color: "#E10098" },
  express: { Icon: SiExpress, color: "#FFFFFF" },
  "express.js": { Icon: SiExpress, color: "#FFFFFF" },
  vue: { Icon: SiVuedotjs, color: "#4FC08D" },
  "vue.js": { Icon: SiVuedotjs, color: "#4FC08D" },
  angular: { Icon: SiAngular, color: "#DD0031" },
  php: { Icon: SiPhp, color: "#8892BF" },
  laravel: { Icon: SiLaravel, color: "#FF2D20" },
  django: { Icon: SiDjango, color: "#FFFFFF" },
  flask: { Icon: SiFlask, color: "#FFFFFF" },
  rust: { Icon: SiRust, color: "#FFFFFF" },
  go: { Icon: SiGo, color: "#00ADD8" },
  golang: { Icon: SiGo, color: "#00ADD8" },
  kubernetes: { Icon: SiKubernetes, color: "#326CE5" },
  aws: { Icon: FaAws, color: "#FF9900" },
  "amazon web services": { Icon: FaAws, color: "#FF9900" },
  "google cloud": { Icon: SiGooglecloud, color: "#4285F4" },
  gcp: { Icon: SiGooglecloud, color: "#4285F4" },
  owasp: { Icon: SiOwasp, color: "#D0D0D0" },
  "burp suite": { Icon: SiBurpsuite, color: "#FF6633" },
  burpsuite: { Icon: SiBurpsuite, color: "#FF6633" },
  hackthebox: { Icon: SiHackthebox, color: "#9FEF00" },
  "hack the box": { Icon: SiHackthebox, color: "#9FEF00" },
  tryhackme: { Icon: SiTryhackme, color: "#C2E24A" },
  portswigger: { Icon: SiPortswigger, color: "#FF6633" },
  zod: { Icon: SiZod, color: "#7A9FE0" },
  jwt: { Icon: SiJsonwebtokens, color: "#FFFFFF" },
  "json web tokens": { Icon: SiJsonwebtokens, color: "#FFFFFF" },
  openssl: { Icon: SiOpenssl, color: "#E06666" },
  ubuntu: { Icon: SiUbuntu, color: "#E95420" },
  debian: { Icon: SiDebian, color: "#D70A53" },
  apache: { Icon: SiApache, color: "#D22128" },
  jest: { Icon: SiJest, color: "#E5455D" },
  eslint: { Icon: SiEslint, color: "#8C97F2" },
  prettier: { Icon: SiPrettier, color: "#F7B93E" },
  windows: { Icon: FaWindows, color: "#4EA6E6" },
  macos: { Icon: SiApple, color: "#FFFFFF" },
  ios: { Icon: SiApple, color: "#FFFFFF" },
  android: { Icon: SiAndroid, color: "#3DDC84" },
};

function lookup(name: string) {
  return TECH_ICONS[name.trim().toLowerCase()];
}

export function TechList({ items }: { items: string[] }) {
  return (
    <div className="tags">
      {items.map((item) => {
        const match = lookup(item);
        return (
          <span key={item} className="tech-badge">
            {match && (
              <match.Icon size={13} color={match.color} aria-hidden="true" />
            )}
            {item}
          </span>
        );
      })}
    </div>
  );
}
